services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6380:6379"  # Host port 6380 -> Container port 6379
